//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoubleT : DbContext
    {
        public DoubleT()
            : base("name=DoubleT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCustomer> TBCustomers { get; set; }
        public virtual DbSet<TBMovie> TBMovies { get; set; }
        public virtual DbSet<TBMovieGenre> TBMovieGenres { get; set; }
        public virtual DbSet<TBReceipt> TBReceipts { get; set; }
        public virtual DbSet<TBRoom> TBRooms { get; set; }
        public virtual DbSet<TBRoomType> TBRoomTypes { get; set; }
        public virtual DbSet<TBSchedule> TBSchedules { get; set; }
        public virtual DbSet<TBSeat> TBSeats { get; set; }
        public virtual DbSet<TBSeatBooking> TBSeatBookings { get; set; }
        public virtual DbSet<TBSeatType> TBSeatTypes { get; set; }
        public virtual DbSet<TBShift> TBShifts { get; set; }
        public virtual DbSet<TBShifttime> TBShifttimes { get; set; }
        public virtual DbSet<TBStaff> TBStaffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
