//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBShift
    {
        public int shift_id { get; set; }
        public System.DateTime shift_date { get; set; }
        public Nullable<int> shifttime_id { get; set; }
        public int staff_id { get; set; }
    
        public virtual TBShifttime TBShifttime { get; set; }
        public virtual TBStaff TBStaff { get; set; }
    }
}
